spring:
  application:
    name: yop

  datasource:
      url: jdbc:h2:mem:mydb
      driverClassName: org.h2.Driver
      username: sa
      password: password
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
      console:
        enabled: true


springdoc:
  swagger-ui:
    path: /swagger.html


my.key.private: jaA0eUlWaOse2CuBBSLscdumyBJBt6Em7wCGWtwkfMY
my.user.private: Usuario

