spring:
  application:
    name: yop

  datasource:
    url: jdbc:mysql://localhost:3306/Interfaces
    username: root
    password: flavio2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


springdoc:
  swagger-ui:
    path: /swagger.html


my.key.private: jaA0eUlWaOse2CuBBSLscdumyBJBt6Em7wCGWtwkfMY
my.user.private: Auth

